version: "3.8"
services:
  v2rayb:
    build:
      context: .
      dockerfile: Dockerfile
    image: v2rayb:latest
    container_name: v2rayb
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - v2rayb-data:/etc/v2rayb
      - /lib/modules:/lib/modules:ro
    environment:
      - V2RAYB_ADDRESS=0.0.0.0:2017

volumes:
  v2rayb-data:
